version: '3'
services:
  db:
    image: postgres:10.4
    networks:
      - database
    ports:
      - '5454:5432'
    env_file:
      - ./database/.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    container_name: postgresql
    hostname: postgresql

  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - back
  #   networks:
  #     - webapp
  #   ports:
  #     - 8080:8080
  #   restart: always
  #   command: ['./wait-for-it.sh', 'back:5500', '--', 'nginx', '-g', 'pid /tmp/nginx.pid; daemon off;']
  #   container_name: front
  #   hostname: front

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    ports:
      - 5500:5500
    depends_on:
      - db
    restart: always
    command: ['./wait-for-it.sh', 'postgresql:5432', '--', 'npm', 'start']
    container_name: backend
    hostname: backend

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
